
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnkdbkjwrcnghhgmhzue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBua2Ria2p3cmNuZ2hoZ21oenVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTc4NzcsImV4cCI6MjA1OTkzMzg3N30.w0tzlFFRtD90DY2KVjT4kvYu9vTZDkA_HJP4EKkqnmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    detectSessionInUrl: true,
    flowType: 'pkce' // Using PKCE flow for more secure authentication
  }
});

// Helper function to check Supabase connection
export const checkSupabaseConnection = async () => {
  try {
    // Just check if we can connect to Supabase by getting the current session
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Supabase connection error:', error);
      return { success: false, message: error.message || 'Unknown error' };
    } else {
      console.log('Supabase connection successful');
      return { success: true, message: 'Connection successful' };
    }
  } catch (err) {
    console.error('Failed to connect to Supabase:', err);
    return { success: false, message: String(err) };
  }
};

// Improved logout function
export const performLogout = async (navigate) => {
  try {
    console.log("Starting logout process...");
    
    // Clear any local storage items related to auth first
    localStorage.removeItem('supabase.auth.token');
    localStorage.removeItem('sb-' + SUPABASE_URL.split('//')[1].split('.')[0] + '-auth-token');
    
    // Attempt to sign out from Supabase
    const { error } = await supabase.auth.signOut({
      scope: 'global' // Ensures all sessions are cleared, not just the current one
    });
    
    if (error) {
      console.error("Logout API error:", error);
      return { success: false, error: error.message };
    }
    
    console.log("Logout API call successful");
    
    // Force clear session state
    await supabase.auth.signOut(); // Additional signout attempt to ensure session is cleared
    
    return { success: true };
  } catch (err) {
    console.error("Exception during logout:", err);
    return { success: false, error: String(err) };
  } finally {
    // Always navigate and reload, even if there was an error
    // This ensures the UI state is reset
    if (navigate) {
      console.log("Navigating away and reloading page");
      // Give a small delay before navigation to ensure auth state is cleared
      setTimeout(() => {
        navigate('/', { replace: true });
        window.location.reload();
      }, 1000);
    }
  }
};

// Legacy debug function, kept for compatibility
export const debugLogout = performLogout;
